# Database Settings
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb;MODE=mysql;
    username: sa
    password:
    driverClassName: org.h2.Driver

  # H2 Settings
  h2:
    console:
      enabled: true
      path: /h2-console

  logging:
    level:
      org:
        springframework.web: debug
  sql:
    init:
      platform: h2
      mode: always
  jpa:
    defer-datasource-initialization: true
